version: '3'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:4.2
    volumes:
      - mongo_data:/data/db
    networks:
      - graylog
    restart: always
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog
    restart: always
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:4.0
    volumes:
      - graylog_data:/usr/share/graylog/data
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=4GHrweeIEasdf09X
      # Password: admin
      #- GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASS}
      #- GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.20.230:9000
      # Set in .env
      # e.g.
      #  HTTP_HOST=192.168.20.230
      #  HTTP_PORT=9000
      - GRAYLOG_HTTP_EXTERNAL_URI=http://${HTTP_HOST}:${HTTP_PORT}/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog UDP 
      - 514:514/udp
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
networks:
  graylog:
    driver: bridge

# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLS}/mongo_data
  es_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLS}/es_data
  graylog_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLS}/graylog_data
